### PR TITLE
[#795] Show error when adding duplicate warc file

### PR DESCRIPTION
**Pull request by kuechensofa**
## Description

Show an error when adding a warc file that has the same filename as an existing file in the collection and do not overwrite the existing file.

## Motivation and Context

See #795 

## Types of changes

- [ ] Replay fix (fixes a replay specific issue)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added or updated tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tw4l** [comment]
Thank you for the bug report and patch @kuechensofa! It would be great if instead of immediately raising an `IOError` when encounting a warc whose names already exists in the collection, we allowed the other warcs (those without naming conflicts) to be added and indexed, and print an error message at the end of the process listing any warcs that weren't able to be added.

Would you be able to make that change? Otherwise happy to do it myself.

**Comment by kuechensofa** [comment]
> Thank you for the bug report and patch @kuechensofa! It would be great if instead of immediately raising an `IOError` when encounting a warc whose names already exists in the collection, we allowed the other warcs (those without naming conflicts) to be added and indexed, and throw the exception at the end of the process with the list of warcs that weren't able to be added.
> 
> Would you be able to make that change? Otherwise happy to do it myself.

Thanks for the reply! I'm happy to implement that change.

**Comment by tw4l** [comment]
thanks @kuechensofa ! merged into `main` and will be included in the next point release :)

**Comment by kuechensofa** [comment]
@tw4l Thanks, for merging! :)

**Pull request merged**
