### PR TITLE
Add locale-dependent handling of first day of week

### PR DESCRIPTION
**Pull request by krakan**
## Description

The Intl.Locale is a proposed standard that provides a way to get the first day of week based on locale or language.
This proposed standard is not yet fully supported by Firefox so in Firefox the first day of week will default to Monday (as specified in ISO-8601). (Switching `static firstDayOfWeek = 1;` to `static firstDayOfWeek = 0;` will make the default Sunday instead.)

## Motivation and Context

In locales where Sunday is not the first day of week it is confusing that the calendar weeks look off by one.

## Screenshots (if appropriate):
April and May 2022 in English
April and May 2022 in Swedish

## Types of changes

- [ ] Replay fix (fixes a replay specific issue)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added or updated tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tw4l** [comment]
Thanks @krakan ! This looks like a good change for a patch release of pywb.

The `pywb/static/vue/vueui.js` file is a build artifact built from the source code in [`/pywb/vueui`](https://github.com/webrecorder/pywb/tree/main/pywb/vueui). Would you mind refactoring this a bit to make the changes in the source code and then rebuild the static bundle from that? The development section of the [contributing guide](https://github.com/webrecorder/pywb/blob/main/CONTRIBUTING.md) has some information on how to do that, but feel free to ask if you have any questions!

**Review by tw4l — CHANGES_REQUESTED** [review]
Requested change: apply changes to source code rather than static build artifact

**Comment by krakan** [comment]
There's still an error though as can actually be seen in the screenshots: 2022-05-01 is a Sunday but is shown as Monday in the Swedish view.

**Comment by krakan** [comment]
There:
2022-12-02-150025_463x303_scrot

**Review by tw4l — APPROVED** [review]
thank you @krakan, this is looking great!

I'm merging this into our 2.7.1-dev branch and we will include the fix in the coming 2.7.1 patch release with attribution to you for the fix :)

**Pull request merged**
